---
analyze_code_task:
  description: Analyze the mobile application code located at {source_code_path} developed
    using {framework}. Extract comprehensive details including functionalities, architecture,
    modules, and core logic.
  expected_output: A detailed code analysis report outlining the application's key
    functionalities, module breakdown, and architectural decisions.
  async_execution: false
  agent: code_analyzer
extract_business_requirements_task:
  description: 'Utilize the code analysis report to extract core business requirements
    and identify essential functionalities. Generate initial UI/UX mockup sketches
    considering the provided business context: {business_context}.'
  expected_output: A comprehensive document summarizing business needs, functional
    requirements, and preliminary UI/UX mockup sketches.
  async_execution: false
  agent: business_mockup_extractor
  context:
  - analyze_code_task
generate_ui_components_task:
  description: Create front-end code components and design prototypes in {target_language}
    based on the UI/UX mockups and business requirements derived from the previous
    analysis.
  expected_output: A set of well-structured and modular front-end code components
    implementing the UI/UX design and fulfilling business requirements in {target_language}.
  async_execution: false
  agent: uiux_developer
  context:
  - extract_business_requirements_task
generate_backend_services_task:
  description: Develop backend services including API integrations, data processing,
    and navigation flows in {target_language} leveraging the technical details provided
    in the code analysis report.
  expected_output: Robust backend services code that includes API calls, service integrations,
    and navigation logic, properly structured for the new app in {target_language}.
  async_execution: false
  agent: backend_developer
  context:
  - analyze_code_task
generate_unit_tests_task:
  description: Based on the generated front-end and backend components, create a comprehensive
    suite of unit tests in {target_language} to ensure proper functionality and stability
    of the new application.
  expected_output: A detailed set of unit tests that thoroughly validate both UI components
    and backend functionalities of the new app.
  async_execution: false
  agent: unit_test_generator
  context:
  - generate_ui_components_task
  - generate_backend_services_task
